image: gcc:9

build:
  stage: build
  script:
    - make O=build
  artifacts:
    paths:
      - build/kernel.raw
  cache:
    paths:
      - build/obj/*.o
      - build/kernel.raw
      - build/kernel.elf
      - build/kernel.S
