name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make O=build

    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel
        path: build/kernel.*
